---
deployment:
  tasks:
    - export DEPLOYPATH=/home/trackszdevsinelo/public_html/sample   #Deployement (Live) directory path      
	    - /bin/cp sample1 $DEPLOYPATH                 #Copy specific file to destination from root
        - /bin/cp /sample1/testr2222 $DEPLOYPATH   #copy specific file from source sub folder
        - /bin cp * $DEPLOYPATH                           #copy all from root 
        - /bin cp /sample2/* $DEPLOYPATH             #copy all from sub folder root
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH