---
deployment:
  tasks:
    - export DEPLOYPATH=/home/trackszdevsinelo/public_html/sample   #Deployement (Live) directory path
    - /bin/cp test1.txt $DEPLOYPATH   # Upload specifc individual file into Deployement folder
	- /bin cp * $DEPLOYPATH #copy all from root 